# Generated by Django 5.0.6 on 2024-07-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='main_course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('simg', models.URLField()),
            ],
        ),
        migrations.RenameField(
            model_name='starters',
            old_name='priceM',
            new_name='price',
        ),
    ]
