# Generated by Django 5.0.6 on 2024-07-08 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_main_course_rename_pricem_starters_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='desserts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('Dimg', models.URLField()),
            ],
        ),
        migrations.RenameField(
            model_name='main_course',
            old_name='simg',
            new_name='Mimg',
        ),
    ]
